apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  loadBalancerIP: 104.42.53.146
  type: LoadBalancer
  ports:
    - port: 80
      targetport: 80
      protocol: TCP
      name: www
  selector:
    app: nginx